### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by supersarma** [YunoHost-Apps/terraforming-mars_ynh#192]
Hello,

I am on Yunohost 12.0.7.
Trying to install this package and getting an error.
There is an Error 404 during the install.

Yunohost log here : https://paste.yunohost.org/raw/acerifijuh

Thank you for your help.

**Comment by Thovi98** [comment]
Thanks for the issue, wasn't aware of it!
Could you please try again with the new update? My take up to 4 hours to be ready, but should solve the issue :)

**Comment by supersarma** [comment]
Merci :)

Everything is fine now with the update. 
All I have to do now is learn to play this beautiful game hehe

Thank you for the quick fix Thomas.

**Comment by Thovi98** [comment]
Thanks for the feedback!
Have fun 🎉
